### ISSUE TITLE
Explore more efficient data structure for Wthdrawal Queue

### ISSUE THREAD

**Issue by fubuloubu** [yearn/yearn-vaults#152]
From Audit Report:

The vault contract manages a withdraw queue. In some locations duplicate checks are being performed. However, in the function `Vault.setWithdrawalQueue(_newQueue)` there are protections against adding the address zero but there is no protection against adding the same address multiple times to the queue.

Additionally, the function `Vault._organizeWithdrawalQueue()` reorganizes the withdrawal queue such that all zero addresses are at the end of the array and none is in-between valid addresses. When adding a strategy to the queue by calling `Vault,addStrategyToQueue(_strategy, *params)` the loop ensures that the new strategy to be added is not in the queue already. We should evaluate to use the loop to put the new strategy into the correct free slot already. This would save the reorganization of the queue done in the next step with `Vautl._organizeWithdrawalQueue.()`

---

Explore a data structure that could enable constant-time membership checks as well as linear time insertion/removal/iteration.

NOTE: research adding this directly to Vyper as an additional data type available e.g. `OrderedSet`

**Comment by steffenix** [comment]
The first part of this issue is resolved by https://github.com/yearn/yearn-vaults/pull/299

**Comment by Niraj-Kamdar** [comment]
I have created an in-memory set data-structure with simple hash function which can be used to remove duplicates from an array. 
You can checkout the gist at: https://gist.github.com/Niraj-Kamdar/25d47ae6773ea702cc583a1403627cdd

I will profile it for gas cost and if it seems better than the current solution then we can replace it.

**Comment by steffenix** [comment]
@Niraj-Kamdar in our case, this needs to be on our vault, it's written in Vyper.

**Comment by Niraj-Kamdar** [comment]
I think I will be able to convert this into a Vyper code.

**Comment by fubuloubu** [comment]
> I have created an in-memory set data-structure with simple hash function which can be used to remove duplicates from an array.
> You can checkout the gist at: https://gist.github.com/Niraj-Kamdar/25d47ae6773ea702cc583a1403627cdd
> 
> I will profile it for gas cost and if it seems better than the current solution then we can replace it.

Thanks for sharing! As @steffenix said, in order to work for us it would need to be implemented in Vyper. but could also explore the idea of set membership to maintain proper use of the queue.

**Comment by Niraj-Kamdar** [comment]
I will try to convert it into vyper and make it work out for yearn vault

**Comment by Niraj-Kamdar** [comment]
I have converted the code in Vyper and benchmarked it and it seems promising:

### Without Set (current):
```
TestStrategy <Contract>
   └─ constructor             -  avg: 2927246  avg (confirmed): 2927246  low: 2926947  high: 2927375
Vault <Contract>
   ├─ constructor             -  avg: 4650568  avg (confirmed): 4650568  low: 4650568  high: 4650568
   ├─ initialize              -  avg:  354550  avg (confirmed):  354550  low:  354468  high:  354579
   ├─ addStrategy             -  avg:  197132  avg (confirmed):  205796  low:   23914  high:  220661
   ├─ setWithdrawalQueue      -  avg:  115595  avg (confirmed):  289094  low:   28438  high:  289094
   ├─ removeStrategyFromQueue -  avg:   85318  avg (confirmed):  146051  low:   24588  high:  146051
   ├─ setDepositLimit         -  avg:   43852  avg (confirmed):   43852  low:   43852  high:   43852
   ├─ addStrategyToQueue      -  avg:   41719  avg (confirmed):   87202  low:   24562  high:   87202
   ├─ setManagement           -  avg:   28659  avg (confirmed):   28659  low:   28659  high:   28659
   └─ withdrawalQueue         -  avg:   23955  avg (confirmed):   23955  low:   23955  high:   23967  With Set: TestStrategy 
```
### With Set (proposed solution)
```
<Contract>
   └─ constructor             -  avg: 2927246  avg (confirmed): 2927246  low: 2926947  high: 2927375
Vault <Contract>
   ├─ constructor             -  avg: 4774516  avg (confirmed): 4774516  low: 4774516  high: 4774516
   ├─ initialize              -  avg:  354550  avg (confirmed):  354550  low:  354468  high:  354579
   ├─ addStrategy             -  avg:  197132  avg (confirmed):  205796  low:   23914  high:  220661
   ├─ removeStrategyFromQueue -  avg:   85318  avg (confirmed):  146051  low:   24588  high:  146051
   ├─ setWithdrawalQueue      -  avg:   79069  avg (confirmed):  200065  low:   28438  high:  200065
   ├─ setDepositLimit         -  avg:   43852  avg (confirmed):   43852  low:   43852  high:   43852
   ├─ addStrategyToQueue      -  avg:   41719  avg (confirmed):   87202  low:   24562  high:   87202
   ├─ setManagement           -  avg:   28659  avg (confirmed):   28659  low:   28659  high:   28659
   └─ withdrawalQueue         -  avg:   23955  avg (confirmed):   23955  low:   23955  high:   23967
```

As you can see, in proposed solution `setWithdrawalQueue` is only consuming **79069** compared to **115595** gas cost of current solution. This ofcourse comes with slightly high gas cost of constructor from **4650568** to **4774516**.

**Comment by Niraj-Kamdar** [comment]
I can open up a PR if you want to include it.

**Comment by fubuloubu** [comment]
> I can open up a PR if you want to include it.

Yes please!
