### ISSUE TITLE
Etherscan verification doesn't work with proxy v2 vaults

### ISSUE THREAD

**Issue by dougstorm** [yearn/yearn-vaults#189]
e.g
https://etherscan.io/address/0x0e880118C29F095143dDA28e64d95333A9e75A47

These vaults we can only add ABI to them, but when querying params some values are incorrect like token and balances.

![Screen Shot 2021-02-08 at 07 34 55](https://user-images.githubusercontent.com/6074987/107226791-2dfbce80-69e0-11eb-8c3b-74a9ddabc65e.png)
 
Verification helps verify the data in contract and also for users that want to check against the deployed verified code

Not sure if this needs a change in etherscan or is something that we can fix on our end, but wanted to track here since its an issue with v2 vaults.

Not sure if this fix has to be done on the etherscan or its an issue we can fix on our end, tracking it here.

**Comment by banteg** [comment]
Vyper uses a bit non-standard minimal proxy, so it needs to be fixed on Etherscan end.
From our end we can transition to EIP-1167 minimal proxies with the next Vyper and Vault releases.
https://github.com/vyperlang/vyper/pull/2281

**Comment by fubuloubu** [comment]
> Vyper uses a bit non-standard minimal proxy, so it needs to be fixed on Etherscan end.
> From our end we can transition to EIP-1167 minimal proxies with the next Vyper and Vault releases.
> [vyperlang/vyper#2281](https://github.com/vyperlang/vyper/pull/2281)

This would require redeploying the `Registry`, which might be painful but we have other things that need fixing with it (see #179)

Etherscan fix is coming soon, I am in talks with them.
