### ISSUE TITLE
Create a guest list for v2 Curve LP vaults

### ISSUE THREAD

**Issue by fameal** [yearn/yearn-vaults#205]
The guest list can be based on https://github.com/banteg/guest-list

The guest list must allow governance to add guests to the vaults, address by address. 

Addresses in the guest list can deposit into the vault.

**Comment by steffenix** [comment]
Will help on this one

**Comment by fameal** [comment]
@fubuloubu what do you think about using Steffenix guest list for v2 migration?

**Comment by steffenix** [comment]
Code is actually on https://github.com/steffenix/Curve-LP-Vault-manager/pull/1 @fubuloubu made some comments already.

**Comment by steffenix** [comment]
Can I get an update on this one?

**Comment by fubuloubu** [comment]
Next steps here would be to develop a version of `contracts/test/AffiliateToken.sol` that works similar to our v2 Vaults today (e.g. the same mgmt fee structure) and allows those invested in v1 Curve LP Vaults to migrate their funds over. This should be a separate repository, working in concert with the Guest List you've developed and the Vault Registry. Let's talk about it this week.

**Comment by steffenix** [comment]
I have merged https://github.com/steffenix/Curve-LP-Vault-manager/pull/1 into master.
I am free to start the next task @fubuloubu

**Comment by fubuloubu** [comment]
Lets chat tomorrow about the Curve LP stuff!
