### ISSUE TITLE
Add CHI support for strategies

### ISSUE THREAD

**Issue by milkyklim** [yearn/yearn-vaults#21]
As discussed would be useful for `harvest()` calls which should be called even with 500 gwei.

**Comment by emilianobonassi** [comment]
You can easily use this @fubuloubu @milkyklim 

https://github.com/emilianobonassi/gas-saver

Add the modifier in the methods you want and it does automatically the trick ;)

**Comment by fubuloubu** [comment]
would also be really awesome to use gas-savings for deployments of new Vaults (and Strategies), since they are so expensive to deploy

**Comment by Macarse** [comment]
There is also LGT. We should try different approaches before making a decision.

**Comment by fubuloubu** [comment]
I was figuring for harvest and tend the right spot might be to do it with Keep3r stuff.

This issue is quite old at this point, maybe we should rethink?

**Comment by fameal** [comment]
Is this still relevant? It seems that gas tokens are going to be deprecated soon.

**Comment by milkyklim** [comment]
No, @steffenix own PR was closed by himself.
