### ISSUE TITLE
Handle tokens with transfer fees

### ISSUE THREAD

**Issue by fubuloubu** [yearn/yearn-vaults#217]
From audit:

"Some tokens have transfer fees. The withdrawal and deposit will likely have issues in case of transfer fees. The exact issues depend on the implementation specifics of the fees. Please note that USDT is such a token. Currently, USDT transfer fees are set to zero."

**Comment by fameal** [comment]
@fubuloubu can we close this as won't fix?

**Comment by fubuloubu** [comment]
closed by #331
