### ISSUE TITLE
Explore supporting definationary/inflationary/rebalancing tokens

### ISSUE THREAD

**Issue by fubuloubu** [yearn/yearn-vaults#218]
From audit:

"Deflationary, inflationary and rebalancing tokens: For these tokens it is quite hard to make general statements, as their low-level details differ in important aspects. For these tokens it is very important that the strategies are aware of their characteristics and do any internal accounting accordingly."

NOTE: Currently our Vault design does not support these at all, and it remains to be seen if we ever need to support these.

**Comment by fameal** [comment]
@fubuloubu can we close this as _won't fix_? At this point, this version of vaults is not going to support rebalancing tokens.

**Comment by fubuloubu** [comment]
Closed by #331
