### ISSUE TITLE
Increase precision for important calculations based on decimals

### ISSUE THREAD

**Issue by fubuloubu** [yearn/yearn-vaults#221]
There are a couple of really important interactions that need precise math to prevent too much rounding error from integer math flooring results.

Example:
https://github.com/iearn-finance/yearn-vaults/blob/dff2c5c05caf946ace09dae3cbea79c05983160d/contracts/Vault.vy#L792

We tried to fix it a bit like this:
https://github.com/iearn-finance/yearn-vaults/blob/dff2c5c05caf946ace09dae3cbea79c05983160d/contracts/Vault.vy#L883

But really in general, this should be computed a bit more dynamically so we can ensure a certain level of precision based on the decimals value. Think:
```python
precision = 18 - self.decimals if self.decimals <= 18 else 0

calculation = (10 ** precision) * ... calculation here ... / (10 ** precision)
```

**Comment by steffenix** [comment]
Should we do this after the solidity 0.8 code is merged? The changes on `mul -> *` will most likely conflict.

**Comment by fubuloubu** [comment]
> Should we do this after the solidity 0.8 code is merged? The changes on `mul -> *` will most likely conflict.

This is all mostly talking about the Vaults code which would not be affected by this upgrade

**Comment by steffenix** [comment]
Yes indeed vault is vyper code and not solidity!
