### ISSUE TITLE
Update deployment script to match the current procedure

### ISSUE THREAD

**Issue by fameal** [yearn/yearn-vaults#227]
Update deployment script [deploy.py](https://github.com/yearn/yearn-vaults/blob/master/scripts/deploy.py) to match the current procedure to deploy vaults. The current process can be found in [OPERATIONS.md](https://github.com/yearn/yearn-vaults/blob/master/docs/OPERATIONS.md)

**Comment by fameal** [comment]
#228

**Comment by dougstorm** [comment]
also could be good to update so we can pick version of vault to deploy

**Comment by fameal** [comment]
I removed an old warning from the ops manual also #260. Once we have that merged I think we can close this.

**Comment by tabshaikh** [comment]
@fameal maybe this can also be closed?

**Comment by fameal** [comment]
Yes, we can close this.
