### ISSUE TITLE
BackPort the clone feature of BaseStrategy to 0.3.0 release

### ISSUE THREAD

**Issue by dougstorm** [yearn/yearn-vaults#264]
We had two strategies that needed the cloning feature targeting the USDC/DAI vaults '0.3.0' recently and the only approach has been to edit the baseStrategy which is not ideal since they should be pulled from this repo.

One Example ->https://github.com/Mattdwest/poolTogether/blob/v3_downgrade/contracts/BaseStrategyEdited.sol#L859

Ideally there is a new tag/release '0.3.0-1' where they can pull the compatible 0.3.0, long term solution is to migrate all prod vaults out of 0.3.0

**Comment by fubuloubu** [comment]
Given 0.3.4 also contains precision fix for USDC, should we consider just migrating those vaults to 0.3.5?

We can use this as an opportunity to see how well our partners deal with migrations (Fire Drill)

**Comment by dougstorm** [comment]
> Given 0.3.4 also contains precision fix for USDC, should we consider just migrating those vaults to 0.3.5?
> 
> We can use this as an opportunity to see how well our partners deal with migrations (Fire Drill)

Could be a good option, but i would say the base for migration is after the ToB audits to ensure that next migration will be around for a while on the USDC and DAI vaults, i think targeting the post audit release may be better

**Comment by dougstorm** [comment]
I think we need to bump this one, i keep seeing more examples of strategies going to USDC and DAI and migrating may still be months away so we should have this in place.

E.g.

https://github.com/TheRyanMiller/Vesper-Strategies/blob/downgrade030/contracts/BaseStrategyCompatible.sol

Where @TheRyanMiller had to backport it, could we make a branch of the 0.3.0 tag add this change and create a new tag 0.3.0.1?

**Comment by steffenix** [comment]
@fubuloubu @dougstorm 

What is the final decision on this one?

**Comment by tabshaikh** [comment]
@dougstorm Would like to help on this :)

**Comment by steffenix** [comment]
Version 0.4 and 1.0 will be released next week.
0.4 will be the legacy solidity 0.6 version.
1.0 will be the version going forward.
I hope we can migrate the old vaults and we don't have to add the clone method to BaseStrategy 0.3
