### ISSUE TITLE
Vault's initialize should allow to set management

### ISSUE THREAD

**Issue by poolpitako** [yearn/yearn-vaults#266]
Right now the release process of a vault is:

 - Vault.deploy()
 - Vault.initialize()
 - Registry.newRelease(vault)
 - vault.setManagement(sms)
 
 Setting the management should be part of the vault initialize method.

**Comment by steffenix** [comment]
@fubuloubu do you want me to do it?

**Comment by fubuloubu** [comment]
> @fubuloubu do you want me to do it?

Yeah, I think this could target 0.4.0

**Comment by steffenix** [comment]
https://github.com/yearn/yearn-vaults/pull/271
