### ISSUE TITLE
Prevent calling clone on a cloned contract

### ISSUE THREAD

**Issue by fubuloubu** [yearn/yearn-vaults#298]
The `BaseStrategy.clone()` method is present in clones of an original deployed strategy with the feature. That call should be disabled somehow (perhaps `require(address(this).code.length > 45);`?) so that a clone cannot produce a clone of itself (preventing code verification for EIP-1167 proxies from working properly and using extra gas)

NOTE: The EIP-1167 bytecode size is 45 bytes in length

**Comment by steffenix** [comment]
I have tried and added:
```
    function contractSize() public view returns (uint32) {
      uint32 size;
      address addr = address(this);
      assembly {
        size := extcodesize(addr)
      }
      return size;
    }
```

calling the view the clone size is 45 but trying to clone a clone it doesn't revert.

**Comment by fubuloubu** [comment]
Right, it is actually going to get that directly from delegate contract itself, so that won't work...

Yeah, a storage value that is only set in the delegate e.g. `isOriginal = true;` should work, as the storage should be read from the clone not the delegate.

**Comment by steffenix** [comment]
That's what I thought too, will do it
