### ISSUE TITLE
Fix occasional test case failure

### ISSUE THREAD

**Issue by fubuloubu** [yearn/yearn-vaults#305]
Some CI runs are flaky because it occasionally triggers an assertion in the vaults code for `withdraw`
https://github.com/yearn/yearn-vaults/pull/302/checks?check_run_id=2457823927

![image](https://user-images.githubusercontent.com/3859395/116430261-b0906f00-a814-11eb-9212-69d41f0cdb42.png)

Solution is to basically just make sure it doesn't withdraw dust

**Comment by steffenix** [comment]
That happened way to often today, 
I will take care of it.

**Comment by steffenix** [comment]
The issue is coming from the code that does
```
        // If we have extra, deposit back into `_bestVault` for `sender`
        // NOTE: Invariant is `withdrawn <= amount`
        if (withdrawn > amount && amount > 1) {
            // Don't forget to approve the deposit
            if (token.allowance(address(this), address(_bestVault)) < (withdrawn - amount)) {
                token.safeApprove(address(_bestVault), UNLIMITED_APPROVAL); // Vaults are trusted
            }
    
            _bestVault.deposit(withdrawn - amount, sender);
            withdrawn = amount;
        }
```
