### ISSUE TITLE
Div by zero in Vault code

### ISSUE THREAD

**Issue by poolpitako** [yearn/yearn-vaults#306]
To repro:

 - Create a vault
 - Deploy a strategy
 - Deposit a token
 - Make the strategy send ALL tokens to `ZERO_ADDRESS`
 - Call `harvest()`

`_reportLoss()` will revert because `self._totalAssets()` is 0.

Reported by @fp-crypto!

**Comment by fp-crypto** [comment]
I'm working on a test case.
