### ISSUE TITLE
PrecisionFactor is useless

### ISSUE THREAD

**Issue by zgfzgf** [yearn/yearn-vaults#333]
https://github.com/yearn/yearn-vaults/blob/3db9deded94c11b0536214be3fc1ac57b439212c/contracts/Vault.vy#L806

for example: precisionFactor=10 
amount * totalSupply / self._totalAssets()=23.45 float 

not use  precisionFactor
  The results are **23**

use  precisionFactor
precisionFactor*amount * totalSupply / self._totalAssets()=234.5  is 234
234/precisionFactor=234/10=**23**

so precisionFactor is useless

**Comment by steffenix** [comment]
For that particular line, it is useless yes.
On more complex calculations It remains relevant.

**Comment by zgfzgf** [comment]
maybe self.precisionFactor is useless
