### ISSUE TITLE
Consider changing library function call syntax we use

### ISSUE THREAD

**Issue by steffenix** [yearn/yearn-vaults#359]
See :https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2484

**Comment by Niraj-Kamdar** [comment]
Is anyone working on this? If not I would like to give it a shot.

From what I understand we don't want to use `using .. for ...` syntax for contracts.

In BaseStrategy file we can replace following with the `ISafeERC20` interface.
https://github.com/yearn/yearn-vaults/blob/743089546d47d36d0ece31808d85d32abee7f73e/contracts/BaseStrategy.sol#L181

https://github.com/yearn/yearn-vaults/blob/743089546d47d36d0ece31808d85d32abee7f73e/contracts/BaseStrategy.sol#L332-L333

**Comment by steffenix** [comment]
I am gonna do it.
