### ISSUE TITLE
Question about degradation

### ISSUE THREAD

**Issue by t4sk** [yearn/yearn-vaults#372]
https://github.com/yearn/yearn-vaults/blob/master/contracts/Vault.vy#L296

Above time to 100% degradation is set to  `DEGRADATION_COEFFICIENT * 46 / 10 ** 6 `

`10 ** 6 / 46 = 21739`  is slightly over 6 hours (21600 seconds)

Any clarification about how the number above was derived? Why not just use `21600` instead?

**Comment by t4sk** [comment]
Should I create a PR to change it to 21600?

**Comment by steffenix** [comment]
It's not set to 21600 but calculated based on DEGRADATION_COEFFICIENT which makes it slightly different from 21600. 

It's better to keep the calculation to reduce human errors if the DEGRADATION_COEFFICIENT is changed for example.
