### ISSUE TITLE
ReportLoss problem

### ISSUE THREAD

**Issue by zgfzgf** [yearn/yearn-vaults#384]
suggest:
_reportLoss(strategy: address, loss: uint256, value: uint256)
value is withdraw value
loss should be associated with value.

now:
for example
loss 10  withdraw  value 100
loss 10  withdraw  value 1000
ratio_change is same. it isn't reasonable
https://github.com/yearn/yearn-vaults/blob/78c6b0d5afb4448fd40341decdd8b753a9846e90/contracts/Vault.vy#L960-L979

**Comment by steffenix** [comment]
You have a parameter called `maxLoss` that prevents `withdraw` with too much loss.

**Comment by zgfzgf** [comment]
My main point is that the adjustment of debtRatio is unreasonable. @steffenix @fubuloubu

**Comment by fubuloubu** [comment]
The change in ratio is related to the ratio of loss to total debt. The withdrawal size is a separate concern. This is clearer if you think about a withdrawal that withdraws from multiple strategies to fill out.

The `maxLoss` parameter that @steffenix is talking about is the ratio of the total loss (across multiple strategies) and the withdrawal size, which works like how you're expecting.

**Comment by zgfzgf** [comment]
report -> _reportLoss  
strategy A:  prepareReturn 100   loss 10
strategy B:  prepareReturn 1000 loss 10  
A,B update ratio_change is same. Is it reasonable？

strategy A should change more ratio.

**Comment by fubuloubu** [comment]
> strategy A should change more ratio.

Agreed. But how is it not currently?
