### ISSUE TITLE
Remove strings from require() to reduce contract size

### ISSUE THREAD

**Issue by poolpitako** [yearn/yearn-vaults#417]
We have a lot of `require()` with strings and the ones hurting the most are the ones in modifiers which are copied over and over again.

I did a small test removing all strings from `require()` and that reduces a contract size by 2% aprox. 

Here's an example of the change needed:

Original:
```
modifier onlyGovernance() {
        require(msg.sender == governance(), "!authorized");
        _;
}
```

Finalized:
```
modifier onlyGovernance() {
        require(msg.sender == governance());
        _;
}
```

**Comment by Tylryan** [comment]
Hey guys! Just trying to contribute. This seems like something I could do. Do I have the go ahead? Thanks!

**Comment by fameal** [comment]
That's great! Yes, just go ahead

**Comment by Niraj-Kamdar** [comment]
Instead of removing  it, use this feature of brownie: https://eth-brownie.readthedocs.io/en/stable/tests-pytest-intro.html#developer-revert-comments.
```
modifier onlyGovernance() {
        require(msg.sender == governance()); // dev: "!authorized"
        _;
}
```
This can also be useful while testing.

**Comment by steffenix** [comment]
https://github.com/yearn/yearn-vaults/pull/422

**Comment by Niraj-Kamdar** [comment]
@steffenix instead of removing assertion message completely, we should use dev comments so that we can still assert that while testing and save gas cost at the same time.

**Comment by steffenix** [comment]
It's ok has it is

**Comment by steffenix** [comment]
That will only help with testing but not on chain i don't see a benefit

**Comment by Niraj-Kamdar** [comment]
IMO, It can be helpful while debugging.

**Comment by Niraj-Kamdar** [comment]
Also, if function has multiple modifiers, we can test correctly which modifier resulted in revert.

**Comment by steffenix** [comment]
history[-1].call_trace
