### ISSUE TITLE
Replace modifiers with functions to reduce contract size

### ISSUE THREAD

**Issue by poolpitako** [yearn/yearn-vaults#418]
Two possibilities here:

Original:
```
modifier onlyGovernance() {
    require(msg.sender == governance(), "!authorized");
    _;
}
```

Option 1:

```
function _onlyGovernance() internal {
  require(msg.sender == governance(), "!authorized");
}

modifier onlyGovernance() {
    _onlyGovernance();
    _;
}
```

Option 2:
```
function _onlyGovernance() internal {
  require(msg.sender == governance(), "!authorized");
}

and call `_onlyGovernance();` instead of the modifier
```

This will reduce around 1% the final contract size.

I would go with option 2 since it helps with code coverage. Modifiers are not really well supported.

**Comment by banteg** [comment]
For context, modifiers inline the entire function body, not the other way around, as commonly believed.

**Comment by steffenix** [comment]
https://github.com/yearn/yearn-vaults/pull/422
