### ISSUE TITLE
why pendingGovernance isn't public in Vault.vy?

### ISSUE THREAD

**Issue by zgfzgf** [yearn/yearn-vaults#423]
https://github.com/yearn/yearn-vaults/blob/c42e6ad4587f8c77d9f3c70ca52941c660660cf0/contracts/Registry.vy#L35
#395

**Comment by zgfzgf** [comment]
@fubuloubu Why is that? don't get it

**Comment by steffenix** [comment]
There is no need to have `pendingGovernance` public.
