### ISSUE TITLE
get error in vscode

### ISSUE THREAD

**Issue by yujianFresh** [yearn/yearn-vaults#424]
hi,guys, i run this project well in ternimal, but got error in vscode IDE, more details on 

[brownie issue](https://github.com/eth-brownie/brownie/issues/1128)

can anyone help me ?

**Comment by steffenix** [comment]
That will need to be fixed on https://github.com/tintinweb/vscode-vyper it's not related to yearn.
It shouldn't be an issue for you to keep building.
