### ISSUE TITLE
Smart Contract Error in sUSD v2 Vault

### ISSUE THREAD

**Issue by michaelmowry** [yearn/yearn-vaults#450]
## Description

When trying to withdraw from the sUSD v2 vault in MetaMask I get the following: "ALERT: Transaction Error: Exception thrown in contract code" and over a $500 transaction fee.

## Steps to reproduce

Open the sUSD v2 vault and attempt to withdrawal a balance.

**Expected behavior**
Ability to withdrawal without indication of a contract error and a reasonable withdrawal fee.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/7070665/126049630-3701768c-4657-4233-b335-9702e9f028db.png)

## Versions
- Source link: https://yearn.finance/vaults - sUSD v2 vault
- Brave Browser 1.26.77
- MetaMask 9.8.0

**Comment by fubuloubu** [comment]
Can you show us what the "data" field says?

**Comment by pandadefi** [comment]
I see you have dicussed this on discord https://discord.com/channels/734804446353031319/740414025481060382/866063632234971167
