### ISSUE TITLE
How to migrate an old vault's asset to a new vault.

### ISSUE THREAD

**Issue by hero5512** [yearn/yearn-vaults#457]
From the Vault.vy contract, I know how to migrate a strategy (deposit all underlying to the new strategy). But It seems like we can't migrate vault. How to migrate an old vault's asset to a new vault. thx

**Comment by pandadefi** [comment]
You have to get the users to migrate from one vault to an other.

**Comment by hero5512** [comment]
> You have to get the users to migrate from one vault to an other.

Why don't we use a proxy vault which maintaining contract storage. When we need to migrate to a new contract, we can reset the logic contract as many other defi does.

**Comment by pandadefi** [comment]
For safety/trust with a proxy some malicious dev could potentially take out all the funds from the vault.
