### ISSUE TITLE
Add Invariant check for BaseStrategy on pre 0.4.3 tags for enforcing withdrawal checks

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-vaults#461]
The sanity check line below is a backward compatible fix to enforce that extending contracts from BaseStrategy keep this invariant on withdrawal operations.

<img width="1078" alt="Screen Shot 2021-08-12 at 11 54 00" src="https://user-images.githubusercontent.com/6074987/129245202-0dbc00ee-3be0-4e96-915c-33349b87909c.png">

As per discussion it was suggested we add this fix to all pre 0.4.3 releases tags as -2. e.g 0.3.5-2 tag to contain this backported fix into baseStrategy

**Comment by pandadefi** [comment]
On it!

**Comment by pandadefi** [comment]
All done

**Comment by pandadefi** [comment]
Also added a PR for main
https://github.com/yearn/yearn-vaults/pull/462
