### ISSUE TITLE
Registry.vy and Vault.vy vyper versions do not match

### ISSUE THREAD

**Issue by poolpitako** [yearn/yearn-vaults#463]
Registry is using 0.2.11 https://github.com/yearn/yearn-vaults/blob/main/contracts/Registry.vy#L1
Vault is using 0.2.12 https://github.com/yearn/yearn-vaults/blob/main/contracts/Vault.vy#L1

why?

**Comment by pandadefi** [comment]
@fubuloubu didn't wanted to update the version until we do a new release

**Comment by poolpitako** [comment]
@banteg also mentioned that the versions are matching the on chain deployment. :+1:

Closing.
