### ISSUE TITLE
Add Slither Support to CI

### ISSUE THREAD

**Issue by fubuloubu** [yearn/yearn-vaults#478]
https://github.com/yearn/yearn-vaults/blob/a113064afd59ecac6ae4f8ed9bfe0d0d00c727a3/.github/workflows/lint.yaml#L98

**Comment by sambacha** [comment]
@mohitsaxenaknoldus if you are interested in doing this we can work on something I think will be of better usage, and can provide additional compensation, lmk if you are interested!

**Comment by mohitsaxenaknoldus** [comment]
> @mohitsaxenaknoldus if you are interested in doing this we can work on something I think will be of better usage, and can provide additional compensation, lmk if you are interested!

Yeah sure, just let me know what additional scripts you talking about. I just need more info here on what needs to be done.
