### ISSUE TITLE
Revoke should allow vault management role to call

### ISSUE THREAD

**Issue by fp-crypto** [yearn/yearn-vaults#480]
Let vault `management`(self.management) to call revokeStrategy.
 
https://github.com/yearn/yearn-vaults/blob/b626994c5ca2ed4455053809cdd5b75bd567ccbf/contracts/Vault.vy#L1385

**Comment by ankitiitb1069** [comment]
Added changes in this branch, what is process of raising a PR https://github.com/ankitiitb1069/yearn-vaults/tree/revoke-allow-vault-management

**Comment by pandadefi** [comment]
You are missing some tests to assert that is working properly

Le mar. 2 nov. 2021, 21:40, Ankit Parashar ***@***.***> a
écrit :

**Comment by pandadefi** [comment]
You are missing some tests to assert that is working properly

**Comment by ankitiitb1069** [comment]
Added unit tests as well to assert that it is working properly
