### ISSUE TITLE
What happened with the yETH or yWETH token?

### ISSUE THREAD

**Issue by bitcoinmeetups** [yearn/yearn-vaults#498]
Hello,

I'm MB. A very nice and polite guy.

What happened with the yETH or yWETH token?

A few years ago or so there was this new token available through your dapp. It was called yETH or yWETH or something like that. I invested 1 ETH in it and got 1 yETH or yWETH in return. This is my wallet:

https://etherscan.io/address/0xaDA9eDB16C18463a07cC64bC32DA620728b9b2b2

But now I cannot sell it. We are still 657 holders of this asset. What happened with it and is it possible to sell it somewhere?

**Comment by pandadefi** [comment]
Hello Sir,

The vault you have used as been replaced with our version 2 vault, you can still withdraw your token one way to do it is by using the etherscan contract tab https://etherscan.io/address/0xe1237aA7f535b0CC33Fd973D66cBf830354D16c7#writeContract

On this page connect your web3 wallet then use the function called withdrawAll, you will get your WETH back.
