### ISSUE TITLE
Add Event in Sweep Function

### ISSUE THREAD

**Issue by rareweasel** [yearn/yearn-vaults#504]
Add event at the end of the `sweep` function to track the tokens transferred to governance.

Sweep function [link](https://github.com/yearn/yearn-vaults/blob/v0.4.3/contracts/BaseStrategy.sol#L888).

Target Tag/Branch

https://github.com/yearn/yearn-vaults/tree/v0.4.3

**Comment by pandadefi** [comment]
Token being an erc20 can't the standard erc20 transfer function work here ?

**Comment by bsamuels453** [comment]
@pandadefi in this case, erc20 transfer events aren't adequate. 

This request is primarily for subgraph support, and the subgraph can only listen for erc20 Transfer events for tokens whose addresses it knows about ahead of time. Unfortunately it can't subscribe to all erc20 Transfer events globally, so in this case the event needs to be emitted by the Strategy/Vault.
