### ISSUE TITLE
Add Event in SetLockedProfitDegradation

### ISSUE THREAD

**Issue by rareweasel** [yearn/yearn-vaults#505]
Add event at the end of the `setLockedProfitDegradation` function.

`setLockedProfitDegradation` function [link](https://github.com/yearn/yearn-vaults/blob/v0.4.3/contracts/Vault.vy#L425).

Target Tag/Branch

https://github.com/yearn/yearn-vaults/tree/v0.4.3

**Comment by pandadefi** [comment]
This changes are on the vault, this will go to main since we can't patch vault version only BaseStrategy.
