### ISSUE TITLE
Automatically verify sources on deployment

### ISSUE THREAD

**Issue by fubuloubu** [yearn/yearn-vaults#80]
Brownie needs this: https://github.com/eth-brownie/brownie/issues/411

**Comment by steffenix** [comment]
https://github.com/iearn-finance/yearn-vaults/pull/188
https://github.com/iearn-finance/brownie-strategy-mix/pull/19

**Comment by fubuloubu** [comment]
Verify #188 solves this by deploying all contracts on Ropsten, and we can close

**Comment by steffenix** [comment]
The issue was:

```
TypeError: Etherscan does not support API verification of source code for vyper contracts. You need to verify the source manually.
```

But that was tested on kovan.

**Comment by fubuloubu** [comment]
Oh weird, so Kovan works but Mainnet doesn't? Or just Ropsten doesn't?

I guess make sure the script can handle that failing

**Comment by steffenix** [comment]
I got this issue on kovan, maybe other networks aren't behaving the same way but I don't think that's an issue with the network more of an issue with etherscan.

**Comment by steffenix** [comment]
Just retried on kovan and got the same error again.

**Comment by steffenix** [comment]
```
TypeError: Etherscan does not support API verification of source code for vyper contracts. You need to verify the source manually
```
