### ISSUE TITLE
Deposit tokens with Permit

### ISSUE THREAD

**Issue by dmihal** [yearn/yearn-vaults#93]
Allow depositing tokens with permit(), so users don't need to send a second approve() call

**Comment by fubuloubu** [comment]
Current strategy for this is to basically create a helper contract that wraps Vaults where the token implements the permit operation. It can actually be generalized to support gas-less deposits and withdraws utilizing Keep3r as a relay network.

See @banteg's repository here: https://github.com/banteg/permit-deposit

**Comment by fubuloubu** [comment]
Additional question is if we should add a variable to the Vault to display what the accepted wrapper is for allowing gas-less transactions, if one exists. This would allow automating the detection of this feature per-vault

**Comment by steffenix** [comment]
@fubuloubu @fameal What do we do with this one?

**Comment by fubuloubu** [comment]
BaseWrapper snd yToken solve this
